# Generated by Django 5.1.2 on 2024-11-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gotti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberopendiente',
            name='horario',
            field=models.DateField(null=True),
        ),
    ]
