# Generated by Django 5.1.3 on 2024-11-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gotti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbero',
            name='telefono',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
